### ISSUE TITLE
Deprecated constructors

### ISSUE THREAD

**Issue by drachels** [davosmith/moodle-objectives#1]
I just switched my server over to using PHP 7.0.7 and got the following debug message;
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; block_objectives_class has a deprecated constructor in /var/www/moodle3dev/moodle/blocks/objectives/lib.php on line 21

Doesn't affect my use of the block, just thought I would let you know about it.

**Comment by davosmith** [comment]
I've pushed a couple of commits that fix that problem and also do a general tidy-up of the code.

I'll probably push this out to Moodle.org at some point (probably around the time I'm testing against Moodle 3.2).

**Comment by drachels** [comment]
Thanks, I'll grab a copy for my server running PHP 7.0.7.
