### ISSUE TITLE
Is it hardcoded?

### ISSUE THREAD

**Issue by dinism** [davosmith/moodle-objectives#3]
The text "By the end of this lesson you should be able to..." is hardcoded to english?
![imagem](https://user-images.githubusercontent.com/14828021/118378370-555bcc00-b5cb-11eb-97da-703a76489d4a.png)
I translated it (PT-PT) but it still show in english?
Am i doing anything wrong?

Thanks

**Comment by davosmith** [comment]
It's a configurable setting on the block, with the default set by the language string.

**Comment by dinism** [comment]
I found it. Sorry abou this!
![imagem](https://user-images.githubusercontent.com/14828021/118379819-6c072080-b5d5-11eb-9bf6-254d98ba6d5b.png)
